version: "3.3"


networks:
  backend:

services:
  # attendance-data: 
  #   container_name: attendance-sql-server
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment: 
  #     - SA_PASSWORD=2Secure*Password2
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1431:1433"
  #   networks:
  #     - backend

  admission-data: 
    container_name: admission-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    ports:
      - "1432:1433"
    networks:
      - backend

  # subject-data: 
  #   container_name: subject-sql-server
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment: 
  #     - SA_PASSWORD=2Secure*Password2
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1433:1433"
  #   networks:
  #     - backend

  # apigateway:
  #   container_name: api-gateway
  #   image: ${DOCKER_REGISTRY-}apigateway:1.0
  #   build:
  #     context: APIGateway/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5128:80"
  #   networks:
  #     - backend

  # attendance:
  #   container_name: attendance-api
  #   image: ${DOCKER_REGISTRY-}attendance
  #   build:
  #     context: StudentAttendanceManagement/
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend

  # admission:
  #   container_name: admission-api
  #   image: ${DOCKER_REGISTRY-}admission:1.0
  #   build:
  #     context: StudentAdmissionManagement/
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend

  # subject:
  #   container_name: subject-api
  #   image: ${DOCKER_REGISTRY-}subject
  #   build:
  #     context: RegisterSubject/
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend